### ISSUE TITLE
config.h is not included

### ISSUE THREAD

**Issue by rooterkyberian** [darconeous/smcp#18]
I have run into problems when I tried to compile `smcp` for MIPS with OpenWrt toolkit. If needed I will post full compilation logs, but please just take a look at macros use in https://github.com/darconeous/smcp/blob/08e822e86a/src/smcp/smcp-missing.h . These `ifdef`'s refer to macros defined in `config.h`, but it is never included, until `smcp-missing.c`, which results in undefined references. In my particular case error was ``undefined reference to `___smcp_strlcat'``.

It compiled fine after including the `config.h` (https://github.com/rooterkyberian/openwrt-rt-feed/blob/bfed0ba3b3ffdbc8448c8c1fd7b62632ac5b89c4/smcp/patches/010-include_config_header_fix.patch , I guess it makes the include in .c file unnecessary).

**Comment by darconeous** [comment]
Not sure how I managed to use SMCP this far without noticing this. Thanks for catching it, will fix!

**Comment by darconeous** [comment]
Fixed by d87af6f59a47520fd9a34cf353329df789a646d5.
