### ISSUE TITLE
IPv4 support for Linux

### ISSUE THREAD

**Issue by rooterkyberian** [darconeous/smcp#19]
Currently `smcp` seems to have only limited support for IPv4. In fact for it to even work without IPv6 kernel module it must be compiled with `SMCP_BSD_SOCKETS_NET_FAMILY=AF_INET` macro (it would be nice to have that option in ./configure). After doing that I run into problem of `IPPROTO_IPV4` being undefined, which was easily fixed by changing it to `IPPROTO_IP` ( https://github.com/rooterkyberian/openwrt-rt-feed/blob/46dfdbc6245c8171b3ed8b1fcbe9254a1faa2dfe/smcp/patches/020-IPPROTO_fix.patch ). With this modification it functioned properly without ipv6 kmod on openwrt platform.

Ideally when "Address family not supported by protocol" error happens application should fallback to IPv4 gracefully (right now it just exits).

**Comment by darconeous** [comment]
Excellent points. I'll take your patch and also add a configure script option to use only IPv4 BSD sockets. SMCP does do IPv4 when compiled with IPv6 support, but it requires using the IPv4 backward compatibility mode.

I'm hesitant at the moment to try implementing fallbacks. There are a lot of other features I'd rather implement first. But there's little excuse to not go ahead and make the IPv4-version a bit easier to use.

**Comment by darconeous** [comment]
Your later point about `IPPROTO_IP` has been addressed in recent updates.

I'm considering doing a hefty update to the BSD platform to use IPv4 sockets for IPv4 traffic and IPv6 sockets only for IPv6 traffic. In the mean time I'll go ahead and add that configure flag.

**Comment by darconeous** [comment]
As of commit `6228af07fb9` on the `master` branch, you can now specify that SMCP be built with native-IPv4-only by using the following configuration option:

    ./configure --with-address-family=inet
