### ISSUE TITLE
Cannot compile files

### ISSUE THREAD

**Issue by shantanoo-desai** [darconeous/smcp#20]
hello,
I am making a file which acts as a coap-server and prints whatever value has been passed through a border router to a native Linux PC. 

I have made the file in the Examples folder and everytime I do the following 
<pre> ~$ make clean all
           ~$ make all
</pre>
all the compiled examples from 1 to 4 show up but not the specific file that i want to work with..
I updated the Makefile.am as accordingly  but the file neither shows up during the <pre>make clean</pre> nor <pre>make all </pre> 

the Makefile.am is as follows
<pre>
INCLUDES = -I.. -I$(top_srcdir)/src
#AM_CFLAGS = @CFLAGS@ @WARN_CFLAGS@

noinst_PROGRAMS =

noinst_PROGRAMS += example-1
example_1_SOURCES = example-1.c
example_1_LDADD = ../smcp/libsmcp.la

noinst_PROGRAMS += example-2
example_2_SOURCES = example-2.c
example_2_LDADD = ../smcp/libsmcp.la

noinst_PROGRAMS += example-3
example_3_SOURCES = example-3.c
example_3_LDADD = ../smcp/libsmcp.la

noinst_PROGRAMS += example-4
example_4_SOURCES = example-4.c
example_4_LDADD = ../smcp/libsmcp.la

noinst_PROGRAMS += coap-server
coap_server_SOURCES = coap-server.c
coap_server_LDADD = ../smcp/libsmcp.la

DISTCLEANFILES = .deps Makefile
</pre>

any help would be really appreciated.
thanks
Shan

**Comment by shantanoo-desai** [comment]
Hi recent updates:

I managed to the trace all the mentions of *example-* in the Makefile.in which was also in my folder and added similar coap-server lines to the Makefile.  

Now the files compile but I am not sure if this is the right way to do it everytime i add a new .c file to the folder.

This looks like a sneaky way to get things done.

Any guidance would be helpful for the future.

Thanks
Shan

**Comment by darconeous** [comment]
SMCP uses Autotools to manage makefiles and such.

You are probably better off compiling and installing the libsmcp library and then compiling and linking against that.

But you can get what you are doing to work by running the bootstrap script: "./bootstrap.sh". You will need automake and autoconf installed, though.

-- Robert Quattlebaum
