### ISSUE TITLE
use on bare metal systems possible?

### ISSUE THREAD

**Issue by a-zen** [darconeous/smcp#21]
Hi,

can this library used on bare metal system and if so how?
I'm currently trying to cross compile the library to `arm-none-eabi`.
I also set the options:

    #define SMCP_EMBEDDED     (1)
    #define SMCP_AVOID_PRINTF (1)
    #define SMCP_AVOID_MALLOC (1)

in `coap.h` . Now I'm struggling with getting uip to work.
I'm just wondering if it's worth the effort.

**Comment by darconeous** [comment]
Yes, it should work. Look at the contiki example sources for an example of how it works.

In general, you would use a configuration header to set those options, rather than setting them in random other headers. Setting them in `coap.h` is not adequate because there are lots of other places where it is used. See `smcp-opts.h`. `SMCP_EMBEDDED` should be the only thing you have to set.

**Comment by a-zen** [comment]
Thanks for your reply, will try it.
Regard the option SMCP_AVOID_MALLOC there still is the note:
 @note Not fully implemented yet

There is no support for dynamic memory allocation on my bare metal system.
So even with this option set, it will not work, right?

Also is there a documentation how to use uip as tcp/ip stack. I'm having
trouble compiling smcp with uip.

**Comment by darconeous** [comment]
Some optional features still require malloc, but I believe they are compiled out by default when using the `SMCP_EMBEDDED` option.

As far as documentation, no, I've gotten SMCP working with µIP on Contiki, but I haven't tried getting SMCP working without Contiki. In theory it shouldn't be too difficult to bridge the gap.

Additional contributions of documentation are always welcome. 😊

I'd dive in and help more, but I'm not in a position to be working on SMCP for the next few weeks.

**Comment by darconeous** [comment]
Just wanted to point out that the version of SMCP in the `master` branch is significantly easier to port to bare-metal, since the platform API is now more well-defined.
