### ISSUE TITLE
Cannot run the smcpctl

### ISSUE THREAD

**Issue by shantanoo-desai** [darconeous/smcp#22]
Hello Robert,
I tried cloning the repository and followed the basic steps in the **README**, but somehow the `smcpctl` isn't functioning. I had a similar problem last time when I could not run the multi-line feature of the Command Line tool which got sorted once I installed the following

`apt-get install libreadline-dev libedit-dev`

At this point it doesn't matter if the mutli-line feature runs or not but everytime I test the `smcpctl` for a standard CoAP server like `coap://coap.me` or `coap://vs0.inf.ethz.ch/` this the error I get:

<pre>
smcpctl: error while loading shared libraries: libsmcp.so.0: cannot open shared object file: No such file or directory
</pre>

Any help here or are there other dependencies that I might need in order to overcome this error?

**Comment by shantanoo-desai** [comment]
Update 1:
I am using a __32-bit Ubuntu 14.04 LTS__

I somehow managed to change the above error but now `smcpctl` give me this error:
<pre>
    smcpctl: FATAL-ERROR: Unable to initialize smcp instance! "Address family not supported by protocol" (97)
</pre>

I currently don't have the IPv6 kernel module on the PC and I am using IPv4. Should there be fallback in SMCP scripts for IPv4?

**Comment by shantanoo-desai** [comment]
There had been inconsistencies in the Ubuntu I had been using. Had to do a reinstall of a different kernel version and the tool works great.

Sorry for this issue.

**Comment by darconeous** [comment]
I'm pretty sure the issue you were having was related to issue #19.

**Comment by shantanoo-desai** [comment]
Hi Robert, will have a look into it the Issue I was tackling was my own problem. I had a Kernel which was used for tests and not a generic one! Thanks anyways

**Comment by shantanoo-desai** [comment]
Back to square one with this issue. (__Ubuntu 16.04 LTS 64-bit__)

I am looking around as to why does this error occur.

* Have tried following the step for both `latest-release` and `master` branch and practically there are no errors whilst configuring or installing. 

* I have `automake m4 libreadline-dev libedit-dev` installed.

* the error is with __Shared Libraries__ especially. It keeps showing the following:

        smcpctl: error while loading shared libraries: libsmcp.so.0: cannot open shared object file: No such file or directory


### Note

Removed the previous comments since they did not address this issue in the right context.

**Comment by darconeous** [comment]
Have you tried [LibNyoci](https://github.com/darconeous/libnyoci/)? Most of the code that was in SMCP has been moved over there. Mind giving that a try? If you still run into issues, feel free to open a new issue on that project.
