### ISSUE TITLE
Multicast: how to enable receive multiple responses from different servers?

### ISSUE THREAD

**Issue by paulobrizolara** [darconeous/smcp#41]
When doing a multicast request, may be desirable to receive responses from many endpoints.

Based on my tests, looks like this is not possible with smcp currently.
The request is done correctly, but after receiving a response, the transaction is automatically finished, if SMCP_TRANSACTION_NO_AUTO_END flag is not set (see smcp_handle_response in smcp-transaction.c).

When SMCP_TRANSACTION_NO_AUTO_END is set, the transaction is not finished automatically. However, after a while (and before the timeout time) the transaction is timed-out (in smcp_internal_transaction_timeout).
I believe this is due to the 'resendCallback' been set to NULL after the response arrive.

I will try to do an isolated example to demonstrate the behaviour. 

**Edit**: I am also trying to change the code to make this work (if i succeed i will do a pull request).

**Comment by paulobrizolara** [comment]
Related to that, i was thinking that could be useful if an application could enable the transaction (don't know how yet - maybe using a flag) to continue sending the same multicast request even after receive a response, until timeout, or reach the max number of attempts or some of the callbacks invalidate the transaction. 

This could be useful to ensure that the multicast message will be received by all devices, since cannot exist multicast confirmable messages.
I believe that the RFC mentions this could be done (send the multicast message many times).
I know that this can cause problems (duplicate messages), but depending on application, could be handled (server can ignore duplicate messages).

What do you think?

**Comment by darconeous** [comment]
Thanks for filing this. This is an edge case that I haven't been previously concerned with. Your gut instinct about how it *should* work is correct. Luckily I think it should be pretty easy to fix. I'll take a closer look this weekend.

`NULL`ing out the callback pointers was a hack---we should instead be keeping state internally and just not calling the callbacks (this would allow transactions to be reused without re-initialization).

Regarding resends, I believe I'm currently sending a burst of three packets for multicast, to ensure reliability. Duplicate packet detection prevents any application-level side effects. But this behavior should be much better specified.

**Comment by paulobrizolara** [comment]
I have made an example of a multicast request to illustrate the bug:
https://gist.github.com/paulobrizolara/6d4f9ce1773713fdb7b01c596edffa6c

I put it on a gist because it ended bigger than expected.

The example also shows the different behaviour using the flags:
SMCP_TRANSACTION_NO_AUTO_END -> timeout after a while
SMCP_TRANSACTION_OBSERVE -> never timeouts

Note: i used the node-coap library as server, because it allows open more than one server on same machine. But i believe that the behaviour would be similar if used from different computers or with smcp.

**Comment by paulobrizolara** [comment]
By the way, when executing the examples, i saw that the resends are sent, but only when the client still did not receive responses. Actually, this is the expected behaviour (however, looks like the time between then are very short - only a few milliseconds).

In a multicast request (when multiples responses can be received), perhaps could be useful allow the client to continue resending requests until a timeout. If you think this is appropriate, it probably should be an optional behaviour.

**Comment by darconeous** [comment]
Was that with the changes from #42?

**Comment by darconeous** [comment]
I think this bug should now be fixed. Reopen if this is still a problem.
